import { Metadata } from 'next';
import IncomeList from './_components/IncomeList';

export const metadata: Metadata = {
  title: 'Incomes - My Expense Tracker',
  description: 'Generated by create next app',
};

function Incomes() {
  return (
    <div className='p-10'>
      <IncomeList />
    </div>
  );
}

export default Incomes;
