import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard - My Expense Tracker',
  description: 'Generated by create next app',
};

function Dashboard() {
  return <div>Dashboard</div>;
}

export default Dashboard;
