import { Metadata } from 'next';
import Dashboard from './_components/Dashboard';

export const metadata: Metadata = {
  title: 'Dashboard - My Expense Tracker',
  description: 'Generated by create next app',
};

function DashboardPage() {
  return (
    <div>
      <Dashboard />
    </div>
  );
}

export default DashboardPage;
