import { Metadata } from 'next';
import ExpenseDash from './_components/ExpenseDash';

export const metadata: Metadata = {
  title: 'Expenses - My Expense Tracker',
  description: 'Generated by create next app',
};

function Expenses() {
  return (
    <div className='p-10'>
      <ExpenseDash />
    </div>
  );
}

export default Expenses;
