import { Metadata } from 'next';
import { ShootingStarsAndStarsBackgroundDemo } from './_components/NotFound';

export const metadata: Metadata = {
  title: 'Oops, Sorry! Page not found!',
  description: 'Generated by create next app',
};

export default function NotFound() {
  return (
    <>
      <ShootingStarsAndStarsBackgroundDemo />
    </>
  );
}
