import { Metadata } from 'next';
import BudgetList from './_components/BudgetList';

export const metadata: Metadata = {
  title: 'Budgets - My Expense Tracker',
  description: 'Generated by create next app',
};

function Budgets() {
  return (
    <div className='p-10'>
      <h2 className='font-bold text-3xl'>My Budgets</h2>
      <BudgetList />
    </div>
  );
}

export default Budgets;
