import { UserButton } from '@clerk/nextjs';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard - My Expense Tracker',
  description: 'Generated by create next app',
};

function Dashboard() {
  return (
    <div>
      <UserButton />
    </div>
  );
}

export default Dashboard;
